#!/bin/bash
# Create Herkulio repo on GitHub and push
# Run this manually with your browser

echo "=========================================="
echo "Create Herkulio GitHub Repository"
echo "=========================================="
echo ""
echo "Since the token didn't work for API access, follow these steps:"
echo ""
echo "STEP 1: Create the repo"
echo "----------------------"
echo "1. Go to: https://github.com/new"
echo "2. Repository name: intelligence-platform"
echo "3. Description: Herkulio OSINT Intelligence SaaS Platform"
echo "4. Make it PRIVATE"
echo "5. Click 'Create repository'"
echo ""
echo "STEP 2: Get the SSH URL"
echo "-----------------------"
echo "On the new repo page:"
echo "1. Click the green 'Code' button"
echo "2. Select SSH tab"
echo "3. Copy the URL (looks like: git@github.com:USERNAME/intelligence-platform.git)"
echo ""
echo "STEP 3: Update remote and push"
echo "-------------------------------"
echo "Run these commands:"
echo ""
echo "cd /home/jarvis/herkulio-saas"
echo "git remote set-url origin git@github.com:YOUR_USERNAME/intelligence-platform.git"
echo "git push -u origin main"
echo ""
echo "The SSH key is already configured. It should work immediately."
echo ""
echo "=========================================="
