FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./
RUN npm ci

# Copy app code
COPY app ./app
COPY public ./public
COPY next.config.js ./
COPY jsconfig.json ./

EXPOSE 3000

CMD ["npm", "run", "dev"]
